#- name: "Install angular"
#  npm:
#      name: @angular/cli
#      executable: /opt/node-v6.11.5-linux-x64/bin/npm
#      global: yes

- name: "Install angular"
  command: /opt/node-v6.11.5-linux-x64/bin/npm install gitbook-cli -g


