- name: "Cambia timeouts systemd"
  copy:
      src: template/etc/systemd/system.conf
      dest: /etc/systemd/system.conf
      owner: root
      group: root
      mode: "u=rw,g=r,o=r"

- name: "disable service"
  systemd:    name="{{item}}"  enabled=no  masked=yes
  with_items:
      - pppd-dns.service
      - iio-sensor-proxy.service
      - whoopsie.service
  when: ubuntu2204 is not defined

- name: "disable service"
  systemd: name="{{item}}" enabled=no masked=yes
  with_items:
      - iio-sensor-proxy.service
      - whoopsie.service
  when: ubuntu2204 is defined

#-- 10s
#-- sistemas
#-- rala hosts
