- name: Desinstalar weka basado en repo apt
  apt:
    name: ['weka', 'weka-doc']
    state: absent
    update_cache: yes
    ignore_errors: yes

- name: Extract weka into /opt/weka-3-8-4
  unarchive:
    src: http://10.6.7.11:9393/ftp/packages/weka-3-8-4-azul-zulu-linux.zip
    dest: /opt
    remote_src: yes

- name: Copy desktop icon launcher
  copy:
    src: weka.desktop
    dest: /usr/share/applications/weka.desktop
    mode: '0644'
