- hosts: localhost
  roles:
    - softwareinicial
    - aceleraarranque


  tasks:
  - group:
      name: wireshark
      state: present


  - name: Update repositories cache and install "wireshark" package
    apt:
      name: wireshark
      update_cache: yes
      state: present

  #- name: permisos
  #  command: setcap cap_net_raw, cap_net_admin=eip /usr/bin/dumpcap
