##
## ansible-playbook -i "localhost"  --vault-password-file /etc/vault.txt  /etc/esit-software/desktop-playbook/local.yml --tag debug
#
#



- hosts: localhost, all
  roles:
#   - { role: quitasssd, tags: ['sd'] }
    - { role: projectlibre, tags: ['projectlibre'] }
    - { role: rstudio, tags: ['rstudio'] }
    - { role: vscode, tags: ['vscode'] }
    - { role: rutacorta, tags: ['ir'] }
    - { role: bug-eclipse, tags: ['a'] }
    - { role: compendium, tags: ['a'] }
    - { role: nvm, tags: ['a'] }
    - { role: neurophstudio, tags: ['a'] }
    - { role: softwareinicial, tags: ['si'] }
    - { role: clienteoracle, tags: ['co'] }
    - { role: node, tags: ['edu'] }
    - { role: nodepackages, tags: ['edu'] }
    - { role: hub, tags: ['edu'] }
    - { role: setdefaultpath, tags: ['aa']}
    - { role: kgpg, tags: ['aa'] }
    - { role: cron-actualizasistema, tags: ['n'] }
    - ansibleupdate
    - aceleraarranque
#    - eclipse-java-cpp
    - docker-mysql-php2
    - opencv
    - usuariolocal
    - { role: emacs, tags: ['p'] }
    - { role: mazesolver, tags: ['p'] }
    - { role: weka, tags: ['p'] }
    - { role: docker, tags: ['docker'] }
    - { role: gemas-ruby, tags: ['edu'] }

    # Configure servers with ruby support system wide
    - { role: rvm_io.ruby,
        tags: ruby,
        become: yes,

        rvm1_rubies: ['ruby-2.2.5','ruby-2.3.1'],
        rvm1_install_flags: '--auto-dotfiles',     # Remove --user-install from defaults
        rvm1_install_path: /usr/local/rvm,         # Set to system location
        rvm1_user: root                            # Need root account to access system location
      }


  vars_files:
    - "roles/usuariolocal/vars/local.yml"

  tasks:
  - group:
      name: wireshark
      state: present


  - name: Update repositories cache and install "wireshark" package
    apt:
      name: wireshark
      update_cache: yes
      state: present

  #- name: permisos
  #  command: setcap cap_net_raw, cap_net_admin=eip /usr/bin/dumpcap
