##
## ansible-playbook -i "localhost"  --vault-password-file /etc/vault.txt  /etc/esit-software/desktop-playbook/local.yml --tag debug
#
#
### a ver:

- hosts: localhost, all
  remote_user: root
  gather_facts: yes 
  
  roles:
    - { role: projectlibre, tags: ['projectlibre','onboot'] }
