##
## ansible-playbook -i "localhost"  --vault-password-file /etc/vault.txt  /etc/esit-software/desktop-playbook/local.yml --tag debug
#
#
### a ver:

- hosts: localhost, all
  remote_user: root
  roles:
    - { role: udsclient, tags: ['udsclient'] }
    - { role: env-neupy, tags: ['env-neupy'] }
    - { role: actualiza-sistema-u22, tags: ['actualiza-sistema-u22'] }
    - { role: bug-ldap-stic, tags: ['bug-ldap-stic'] }
    - { role: wol_servicio, tags: ['wol_servicio'] }
    - { role: rutacorta, tags: ['ir'] }
    - { role: mpi, tags: ['mpi'] }
    - { role: cheddar, tags: ['cheddar','onboot'] }
    - { role: copia_hosts-u22, tags: ['hos'] }
    - { role: grubpassword-u22, tags: ['grubpassword-u22'] }
    - { role: fuzzylogic, tags: ['fuzzylogic'] }
    - { role: libpulse, tags: ['lp'] }
    - { role: eclipse-u18, 
        tags: ['e22'],
        eclipse_jee_version: 'eclipse-jee-2022-09-R-linux-gtk-x86_64'
      }
    - { role: python3, tags: ['py'] }
    - { role: installsoftware-u2204, tags: ['sd0'] }
    - { role: nvm, tags: ['a'] }
    - { role: clienteoracle, tags: ['co'] }
    - { role: node, tags: ['edu'] }
    - { role: nodepackages,
        tags: ['edu'],
        node_path: /usr/local/nvm/versions/node/v11.15.0
      }
    - ansibleupdate
    - { role: aceleraarranque,
        ubuntu2204: yes
      }
    - { role: eclipse-java-cpp,
        tags: ['eclipse'],
        eclipse_cpp_version: eclipse-cpp-2022-09-R-linux-gtk-x86_64
      }
    - { role: emacs, tags: ['p'] }
    - { role: mazesolver, tags: ['p'] }
    - { role: weka, 
        tags: ['weka'],
        ubuntu2204: yes
      }
    - { role: gemas-ruby, tags: ['edu'] }
    - { role: rvm_io.ruby,
        tags: ruby,
        become: yes,

        rvm1_rubies: ['ruby-2.7.6'],               # Versiones 2.2.5 y 2.3.1 no instalan en Ubuntu 22.04
        rvm1_install_path: /usr/local/rvm,         # Set to system location
        rvm1_install_flags: "--auto-dotfiles --with-openssl-dir={{ rvm1_install_path }}/usr",     # Remove --user-install from defaults
        rvm1_user: root,                           # Need root account to access system location

        ubuntu2204: yes
      }

    ## Software no instalado en Ubuntu 22.04.
    ## Se ha considerado obsoleto, que viene de serie o no hace falta.
    # - { role: atom, tags: ['atom'] }
    # - { role: profile-env-alias-scripts, tags: ['path'] }
    # - { role: rutacorta, tags: ['ir'] }
    # - { role: bug-eclipse, tags: ['eclipse'] }
    # - { role: compendium, tags: ['a'] }
    # - { role: neurophstudio, tags: ['a'] }
    # - { role: hub, tags: ['edu'] }
    # - { role: kgpg, tags: ['aa'] }
    # - { role: usuariolocal, tags: ['ul']}

#   vars_files:
#     - "roles/usuariolocal/vars/local.yml"

 log_file: /ruta/a/mi_playbook.log

  tasks:
  - group:
      name: wireshark
      state: present

  - name: Update repositories cache and install "wireshark" package
    apt:
      name: wireshark
      update_cache: yes
      state: present

  #- name: permisos
  #  command: setcap cap_net_raw, cap_net_admin=eip /usr/bin/dumpcap
