##
## ansible-playbook -i "localhost"  --vault-password-file /etc/vault.txt  /etc/esit-software/desktop-playbook/local.yml --tag debug
#
#
### a ver:


- hosts: localhost, all
  roles:
    - { role: libpulse, tags: ['lp'] }
    - { role: eclipse-u18, tags: ['e18'] }
    - { role: installsoftware1-u1804, tags: ['sd0'] }
    - { role: installsoftware2-u1804, tags: ['sd1'] }
    - { role: profile-env-alias-scripts, tags: ['sd'] }
#   - { role: quitasssd, tags: ['sd'] }
    - { role: rutacorta, tags: ['ir'] }
    - { role: bug-eclipse, tags: ['eclipse'] }
    - { role: compendium, tags: ['a'] }
    - { role: nvm, tags: ['a'] }
    - { role: neurophstudio, tags: ['a'] }
    - { role: clienteoracle, tags: ['co'] }
    - { role: node, tags: ['edu'] }
    - { role: nodepackages, tags: ['edu'] }
    - { role: hub, tags: ['edu'] }
    - { role: setdefaultpath, tags: ['aa']}
    - { role: kgpg, tags: ['aa'] }
#   - { role: cron-actualizasistema, tags: ['n'] }
    - ansibleupdate
    - aceleraarranque
    - { role: eclipse-java-cpp, tags: ['eclipse']}
    - { role: usuariolocal, tags: ['ul']}
    - { role: emacs, tags: ['p'] }
    - { role: mazesolver, tags: ['p'] }
    - { role: weka, tags: ['p'] }
    - { role: gemas-ruby, tags: ['edu'] }

    # Configure servers with ruby support system wide
    - { role: rvm_io.ruby,
        tags: ruby,
        become: yes,

        rvm1_rubies: ['ruby-2.2.5','ruby-2.3.1'],
        rvm1_install_flags: '--auto-dotfiles',     # Remove --user-install from defaults
        rvm1_install_path: /usr/local/rvm,         # Set to system location
        rvm1_user: root                            # Need root account to access system location
      }

  vars_files:
    - "roles/usuariolocal/vars/local.yml"

  tasks:
  - group:
      name: wireshark
      state: present

  - name: Update repositories cache and install "wireshark" package
    apt:
      name: wireshark
      update_cache: yes
      state: present

  #- name: permisos
  #  command: setcap cap_net_raw, cap_net_admin=eip /usr/bin/dumpcap
