##
## ansible-playbook -i "localhost"  --vault-password-file /etc/vault.txt  /etc/esit-software/desktop-playbook/local.yml --tag debug
#
#
### a ver:


- hosts: ccxxxx.etsii.ull.es
  remote_user: root
  roles:
#     - { role: fuzzylogic, tags: ['fuzzylogic'] }
    # - { role: atom, tags: ['atom'] }
    - { role: libpulse, tags: ['lp'] }
    - { role: eclipse-u18, 
        tags: ['e22'],
        eclipse_jee_version: 'eclipse-jee-2022-09-R-linux-gtk-x86_64'
      }
    - { role: python3, tags: ['py'] }
    - { role: installsoftware-u2204, tags: ['sd0'] }
#     - { role: installsoftware2-u1804, tags: ['sd1'] }
#     - { role: profile-env-alias-scripts, tags: ['path'] }
# NO #   - { role: quitasssd, tags: ['sd'] }
#     - { role: rutacorta, tags: ['ir'] }
#     - { role: bug-eclipse, tags: ['eclipse'] }
#     - { role: compendium, tags: ['a'] }
    - { role: nvm, tags: ['a'] }
#     - { role: neurophstudio, tags: ['a'] }
#     - { role: clienteoracle, tags: ['co'] }
    - { role: node, tags: ['edu'] }
#     - { role: nodepackages, tags: ['edu'] }
# NO     - { role: hub, tags: ['edu'] }
# NO #    - { role: setdefaultpath, tags: ['aa']}
#     - { role: kgpg, tags: ['aa'] }
# NO #   - { role: cron-actualizasistema, tags: ['n'] }
#     - ansibleupdate
#     - aceleraarranque
#     - { role: eclipse-java-cpp, tags: ['eclipse']}
#     - { role: usuariolocal, tags: ['ul']}
    - { role: emacs, tags: ['p'] }
    - { role: mazesolver, tags: ['p'] }
#     - { role: weka, tags: ['weka'] }
#     - { role: gemas-ruby, tags: ['edu'] }

    # Configure servers with ruby support system wide
    - { role: rvm_io.ruby,
        tags: ruby,
        become: yes,

        rvm1_rubies: ['ruby-2.7.6'],               # Versiones 2.2.5 y 2.3.1 no instalan en Ubuntu 22.04
        rvm1_install_flags: '--auto-dotfiles',     # Remove --user-install from defaults
        rvm1_install_path: /usr/local/rvm,         # Set to system location
        rvm1_user: root,                           # Need root account to access system location

        ubuntu2204: yes
      }

#   vars_files:
#     - "roles/usuariolocal/vars/local.yml"

  tasks:
  - group:
      name: wireshark
      state: present

  - name: Update repositories cache and install "wireshark" package
    apt:
      name: wireshark
      update_cache: yes
      state: present

  #- name: permisos
  #  command: setcap cap_net_raw, cap_net_admin=eip /usr/bin/dumpcap
