# roles/udsclient/tasks/main.yml

# === FLAG ===
- name: Definición de la variable del fichero flag
  set_fact:
    flag_path: "/etc/executed_scripts/udsclient-1"  # Incrementar el índice para forzar la ejecución del rol

- name: "Verificar si el rol ha sido ejecutado"
  stat:
    path: "{{ flag_path }}"
  register: flagfile

- name: "Abortar si el rol ha sido ya ejecutado"
  meta: end_play
  when: flagfile.stat.exists

# === TASKS DEL ROL ===
- name: Obtener versión instalada de UDS
  command: dpkg-query -W -f='${Version}' udsclient3
  register: uds_installed_version
  ignore_errors: yes  # Evita fallos si el paquete no está instalado

- name: Instala UDS
  apt:
    deb: http://cc.etsii.ull.es/ftp/packages/udsclient3_3.6.0_all.deb
    state: present
  when: uds_installed_version.stdout is version('3.6.0', '<')

# === FLAG ===
- name: "Crear flag indicando que el rol ha sido ejecutado"
  file:
    path: "{{ flag_path }}"
    state: touch
    mode: '0644'
