- name: Ensure than unattendded Upgrades are disabled
  lineinfile:
    path: /etc/apt/apt.conf.d/20auto-upgrades
    regexp: '^APT::Periodic::Unattended-Upgrade "1";$'
    line: APT::Periodic::Unattended-Upgrade "0";