- name: Install list of packages octave and friends
  apt: 
    state: present 
    update_cache: yes
    name: [octave, liboctave-dev, scilab, fuzzylite] 

- name:  fuzzy
  get_url:
    url:  http://cc.etsii.ull.es/ftp/packages/fuzzy-logic-toolkit-0.4.5.tar.gz
    dest: /opt
    mode: "u=rwx,g=rx,o=rx"

- command: "{{ item }}" 
  with_items:
    - "echo 'pkg install /opt/fuzzy-logic-toolkit-0.4.5.tar.gz' | octave"
    - "echo 'pkg list' | octave"



