# roles/wol_servicio/tasks/main.yml

# === TASKS DEL ROL ===
- name: Install ethtool package
  apt:
    name: ethtool
    state: present

- name: Get network interfaces
  setup:
    filter: 'ansible_interfaces'

- name: Set WoL configuration for the first network interface
  template:
    src: template/wol.service.j2
    dest: /etc/systemd/system/wol.service
  notify: Reload systemd

- name: Enable and start WoL service
  systemd:
    name: wol
    enabled: yes
    state: started
