# roles/wol_servicio/tasks/main.yml

# === TASKS DEL ROL ===
- name: Install ethtool package
  apt:
    name: ethtool
    state: present

- name: Set WoL configuration for the first network interface
  template:
    src: template/wol.service.j2
    dest: /etc/systemd/system/wol.service
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
  notify: Reload systemd

- name: Recargar configuración de systemd
  systemd:
    daemon_reload: yes

- name: Enable and start WoL service
  systemd:
    name: wol
    enabled: yes
    state: started
