#!/bin/bash

apt update -y
apt install -y python3.8-dev python3.8-venv
cd /opt
python3.8 -m venv env-neupy
source /opt/env-neupy/bin/activate
python3.8 -m pip install scipy numpy==1.21.0 neupy==0.6.5 scikit-learn==1.3.2 pyqt5==5.15.2
chmod a+w -R /opt/env-neupy



