#!/bin/bash

echo "=== Instalando Qt en: $(hostname) ==="

cd /opt
rm -Rf /opt/Qt
wget -q --show-progress http://cc.etsii.ull.es/ftp/packages/Qt-5.11.tar.gz
tar xzf Qt-5.11.tar.gz
rm -f Qt-5.11.tar.gz

echo "=== Instalación completada en: $(hostname) ==="