- name: Actualizar los paquetes del sistema
  become: yes
  apt:
    update_cache: yes

- name: Instalar python3.8-dev y python3.8-venv
  become: yes
  apt:
    name: 
      - python3.8-dev
      - python3.8-venv
    state: present
- name: Crear el directorio /opt/env-neupy
  become: yes
  file:
    path: /opt/env-neupy
    state: directory
    mode: "u+rwx,g+rwx,o+rwx"

- name: Crear el entorno virtual
  become: yes
  command: python3.8 -m venv /opt/env-neupy

- name: Activar el entorno virtual
  become: yes
  command: /opt/env-neupy/bin/activate
  args:
    chdir: /opt/env-neupy
  environment:
    VIRTUAL_ENV: /opt/env-neupy

- name: Instalar paquetes en el entorno virtual
  become: yes
  pip:
    name:
      - scipy==1.4.1
      - numpy==1.21.0
      - neupy==0.6.5
      - scikit-learn==1.3.2
      - pyqt5==5.15.2

- name: Dar permisos de escritura a todos en el directorio del entorno virtual
  become: yes
  file:
    path: /opt/env-neupy
    mode: "u+w,g+w,o+w"
    recurse: yes
