- name: Pule y limpia
  command: "{{ item }}" 
  with_items:
    - "apt install -f -y"
    - "dpkg --configure -a"

- name: Install list of packages
  apt: 
    state: present 
    update_cache: yes
    name: [
      'openjdk-21-jdk'
    ]

