- name: Install list of packages
  command: apt-get -f install -y

- name: instala kgpg
  apt: name={{item}} state=installed update_cache=yes autoremove=yes
  with_items:
       - gnupg
       - kgpg

