- name: Pule y limpia
  command: "{{ item }}" 
  with_items:
    - "apt install -f -y"
    - "dpkg --configure -a"

- apt:
     deb: http://cc.etsii.ull.es/ftp/packages/projectlibre_1.8.0-1.deb 

- name: Cambiar nombre de projectlibre a projectlibre-original
  command: mv -f /usr/bin/projectlibre /usr/bin/projectlibre-original2

- name: "Crear archivo /usr/bin/projectlibre"
  copy:
      src: template/usr/bin/projectlibre
      dest: /usr/bin/projectlibre
      owner: root
      group: root
      mode: "u=rwx,g=rx,o=rx"

  

