- name: Pule y limpia
  command: "{{ item }}" 
  with_items:
    - "apt install -f -y"
    - "dpkg --configure -a"

- name: Desinstalar paquete antiguo de ProjectLibre
  ansible.builtin.apt:
    name: projectlibre
    state: absent

- name: Instalar nuevo paquete de ProjectLibre desde URL
  ansible.builtin.apt:
    deb: http://cc.etsii.ull.es/ftp/packages/projectlibre_1.9.3-1.deb
    state: present

- name: Cambiar nombre de projectlibre a projectlibre-original
  command: mv -f /usr/bin/projectlibre /usr/bin/projectlibre-original2

- name: "Crear archivo /usr/bin/projectlibre"
  copy:
      src: template/usr/bin/projectlibre
      dest: /usr/bin/projectlibre
      owner: root
      group: root
      mode: "u=rwx,g=rx,o=rx"

  

