- name: Install list of packages
  apt: 
    state: absent 
    update_cache: yes
    name: [atom] 

- name: Untar 
  unarchive:
    src:  http://cc.etsii.ull.es/ftp/packages/atom-amd64.tar.gz
    dest: /opt/
    remote_src: yes

- name: "ficheros de paquetes"
  copy:
      src: /etc/esit-software/desktop-playbook/roles/atom/template/
      dest: /opt/atom/
      owner: root
      group: root
      mode: "u=rx,g=rx,o=rx"
      remote_src: no

- file:
    path: /opt/.atom 
    state: directory
    mode: 0755

- name: paquetes atom 
  command: "{{ item }}" 
  with_items:
    - "/opt/atom-1.34.0-amd64/resources/app/apm/bin/apm install --packages-file /opt/atom/my_atom_packages.txt"


