#- name: Install list of packages
#  apt: 
#    state: present 
#    update_cache: yes
#    name: [atom] 

- name: Untar 
  unarchive:
    src:  http://cc.etsii.ull.es/ftp/packages/atom-amd64.tar.gz
    dest: /opt/
    remote_src: yes

- name: "ficheros de paquetes"
  copy:
      src: /etc/esit-software/desktop-playbook/roles/atom/template/
      dest: /opt/atom/
      owner: root
      group: root
      mode: "u=rx,g=rx,o=rx"
      remote_src: no

- file:
    path: /opt/.atom 
    state: directory
    mode: 0777

- name: paquetes atom 
  command: "{{ item }}" 
  with_items:
    - "/opt/atom-1.34.0-amd64/resources/app/apm/bin/apm install --packages-file /opt/atom/my_atom_packages.txt"
  environment:
    ATOM_HOME: /opt/.atom   

- name: "link"
  file:
      src: /opt/atom-1.34.0-amd64/atom  
      dest: /usr/local/bin/atom-portable
      owner: root
      group: root
      state: link

- name: "atom hoe"
  copy:
      src: template/etc/profile.d/atom.sh
      dest: /etc/profile.d/atom.sh
      owner: root
      group: root
      mode: "u=rw,g=r,o=r"



