- name: mazesolver
  file:
    path: /opt/mazesolver
    state: directory
    owner: root 
    group: root 
    mode: 0755

- name: mazesolver 
  get_url:
    url: http://cc.etsii.ull.es/ftp/packages/MazeSolver-v1.2.1.jar
    dest: /opt/mazesolver/MazeSolver-v1.2.1.jar
    mode: "u=rwx,g=rx,o=rx" 

- name: mazesolver 3 
  copy:
      src: template/mazesolver
      dest: /usr/local/bin
      owner: root
      group: root
      mode: "u=rwx,g=rx,o=rx"
