- name: "delete eclipse"
  # file: path=/opt/eclipse-java state=absent
  file: path=/opt/eclipse-installer state=absent

- name: "download eclipse"
  unarchive:
      src: /soft/eclipse-jee-neon-3-linux-gtk-x86_64.tar.gz
      dest: /opt/eclipse-java

- name: "link eclipse"
  file:
      src: /opt/eclipse-java/eclipse
      dest: /usr/local/bin/eclipse-java
      owner: root
      group: root
      state: link

- name: "prepare icon eclipse"
  copy:
      src: template/eclipse-java.desktop
      dest: /opt/eclipse-java

- name: "icon eclipse"
  command: desktop-file-install /opt/eclipse-java/eclipse-java.desktop

  # copy:
  #     src: /soft/eclipse-jee-neon-3-linux-gtk-x86_64.tar.gz
  #     dest: /opt/eclipse-jee-neon-3-linux-gtk-x86_64.tar.gz
  #     owner: root
  #     group: root
  #     mode: "u=rw,g=r,o=r"
