- name: Añadir repositorio para python3
  apt_repository:
    repo: ppa:deadsnakes/ppa

- name: Instalar python3
  apt:
    name: python{{ PYTHON_VERSION }}
    state: latest
    update_cache: yes

# - name: Create symbolic link 
#   file:
#     src: "/usr/bin/python{{ PYTHON_VERSION }}"
#     dest: "/usr/bin/python3"
#     state: link

- name: Instalar NLTK
  pip:
    name: nltk
    extra_args: -U

- name: Instalar scikit-learn
  pip:
    name: scikit-learn
    extra_args: -U

- name: Instalar neupy
  pip:
    name: neupy
    extra_args: -U
    executable: "/usr/bin/pip3"
