## FALLA.
- name: "Install CUDA"
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - nvidia-driver-435
    - nvidia-cuda-toolkit
    - clinfo

# añado mas tareas para tener acceso a gpu desde docker
- name: Install NVIDIA CUDA toolkit
  apt:
    name: nvidia-cuda-toolkit
    state: present

- name: Add NVIDIA Docker GPG key
  ansible.builtin.command:
    cmd: "curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | apt-key add -"
    ignore_errors: yes

- name: Add NVIDIA Docker repository
  ansible.builtin.shell: 
    distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
    curl -s -L https://nvidia.github.io/nvidia-docker/${distribution}/nvidia-docker.list | \
    tee /etc/apt/sources.list.d/nvidia-docker.list

- name: Update APT cache
  apt:
    update_cache: yes

- name: Install NVIDIA Container Toolkit
  apt:
    name: nvidia-container-toolkit
    state: present
  become: true

- name: Verify NVIDIA CUDA runtime with Docker
  command: docker run --gpus all --rm nvidia/cuda:12.2.0-runtime-ubuntu22.04 nvidia-smi
  register: docker_test_result
  failed_when: "'failed' in docker_test_result.stderr or docker_test_result.rc != 0"
