- name: Add an apt key by id from a keyserver
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: E298A3A825C0D65DFD57CBB651716619E084DAB9

- name: Añadir repositorio para r-base
  apt_repository:
    repo: deb https://cloud.r-project.org/bin/linux/ubuntu bionic-cran40/

- name: Instalar r-base
  apt:
    name: r-base
    state: latest
    update_cache: yes

- name: Install R-Studio package from the internet.
  apt:
   deb: https://download1.rstudio.org/desktop/bionic/amd64/rstudio-1.2.5033-amd64.deb