- name: Importar la clave
  apt_key:
    url: https://download.sublimetext.com/sublimehq-pub.gpg

- name: Añadir repositorio para sublimetext
  apt_repository:
    repo: deb https://download.sublimetext.com/ apt/stable/

- name: Instalar sublime-text
  apt:
    name: sublime-text
    state: latest