
- name: Uninstall old docker
  apt: name={{item}} state=absent update_cache=yes
  with_items:
       - docker
       - docker-engine
       - docker.io


- name: Install list of packages
  apt: name={{item}} state=installed update_cache=yes
  with_items:
       - apt-transport-https 
       - ca-certificates
       - curl
       - software-properties-common


- name: add an apt key
  apt_key:
       url: https://download.docker.com/linux/ubuntu/gpg 
       state: present

- apt_repository: 
    repo: deb https://download.docker.com/linux/ubuntu xenial stable
    state: present

- name: Install list of packages
  apt: name={{item}} state=installed update_cache=yes
  with_items:
       - docker-ce=17.09.0~ce-0~ubuntu

- name: Install docker-compose
  shell: curl -L https://github.com/docker/compose/releases/download/1.18.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose
  shell: curl -L https://raw.githubusercontent.com/docker/compose/1.18.0/contrib/completion/bash/docker-compose -o /etc/bash_completion.d/docker-compose

- name: Install docker-machine
  shell: curl -L https://github.com/docker/machine/releases/download/v0.13.0/docker-machine-`uname -s`-`uname -m` >/tmp/docker-machine && \
         chmod +x /tmp/docker-machine && \
         cp /tmp/docker-machine /usr/local/bin/docker-machine

- name: Apply executable permissions to docker-machine
  file: path=/usr/local/bin/docker-machine state=file mode=0755

- name: Install Docker Machine bash_completion
  shell: curl -L https://raw.githubusercontent.com/docker/machine/v0.13.0/contrib/completion/bash/{{ item }} > /etc/bash_completion.d/{{ item }}
  args:
    creates: /etc/bash_completion.d/{{ item }}
  with_items:
    - docker-machine-prompt.bash
    - docker-machine-wrapper.bash
    - docker-machine.bash



