
- name: "Make sure NSCD is stopped y no enable"
  service: name=nscd state=stopped enabled=no

- name: instala libnss-ldapd
  apt: pkg=libnss-ldapd state=present update_cache=yes cache_valid_time=1800

  