- name: Hacer upgrade
  apt:
    update_cache: yes
    upgrade: yes
    force_apt_get: yes
    force: yes
    autoremove: yes

- name: Pule y limpia
  command: "{{ item }}" 
  with_items:
    - "apt install -f -y"
    - "dpkg --configure -a"

- name: Remove existent Mysql Workbench packages
  apt:
    pkg:
    - mysql-workbench
    - mysql-workbench-community
    - mysql-workbench-data
    state: absent

- name: Install Mysql-Workbench deb package
  apt:
    deb: http://cc.etsii.ull.es/ftp/packages/mysql-workbench-community_8.0.23-1ubuntu18.04_amd64.deb