- name: Remove existent Mysql Workbench packages
  apt:
    pkg:
    - mysql-workbench
    - mysql-workbench-community
    - mysql-workbench-data
    state: absent

- name: Install Mysql-Workbench deb package
  apt:
    deb: http://cc.etsii.ull.es/ftp/packages/mysql-workbench-community_8.0.23-1ubuntu18.04_amd64.deb