- name: Ejecutar script para instalación de Docker rootless
  ansible.builtin.shell:
    cmd: "../no-ansible-scripts/install-docker-rootless-u22.04.sh"
    chdir: "/tmp"  # Cambia el directorio si es necesario
  become: yes